# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dpma-service-registry-1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_4295ab52979745cfa2c0fbfe5ef69e53 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_7fe584e3b908425d900505d505122a0f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_4295ab52979745cfa2c0fbfe5ef69e53 }}/dotnet/aspnet:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dpma-service-registry-1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_63c3b57682204b0c8499e086b3150dc3 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_4295ab52979745cfa2c0fbfe5ef69e53 }}/dotnet/aspnet:${{ github.sha }}'